version: '3.1'

services:
  mysql:
    image: mysql
    container_name: mysql-fuel
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: combDb
      MYSQL_USER: admin
      MYSQL_PASSWORD: qwe123
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: 'redis:latest'
    container_name: redis-fuel
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:
