version: '3.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: combDb
      MYSQL_USER: admin
      MYSQL_PASSWORD: qwe123
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"